{% set name = "hug" %}
{% set version = "2.4.0" %}
{% set sha256 = "aa60ab69d1939f327ee973f2109f63bc78a5b30b19f433e253e456c233cc2bc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hug/hug-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - hug = hug:development_runner.hug.interface.cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - falcon >=1.4.1
    - requests >=2.9.1
test:
  imports:
    - hug

  commands:
    - hug --help

about:
  home: http://www.hug.rest/
  license: MIT
  license_file: LICENSE
  summary: |
    A Python framework that makes developing APIs as simple as possible,
    but no simpler.
  description: |
    hug aims to make developing Python driven APIs as simple as possible, but no
    simpler. As a result, it drastically simplifies Python API development.
    With hug, design and develop your API once, then expose it however your
    clients need to consume it. Be it locally, over HTTP, or through the command
    line - hug is the fastest and most modern way to create APIs on Python3.
  dev_url: https://github.com/timothycrosley/hug

extra:
  recipe-maintainers:
    - daf
