{% set version = "2.6.1" %}

package:
  name: hug
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hug/hug-{{ version }}.tar.gz
  sha256: b0edace2acb618873779c9ce6ecf9165db54fef95c22262f5700fcdd9febaec9

build:
  skip: true  # [py<36]
  entry_points:
    - hug = hug:development_runner.hug.interface.cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - pytest-runner
  run:
    - python
    - falcon ==2.0.0
    - requests
test:
  imports:
    - hug

test:
  imports:
    - hug
  commands:
    - pip check
    - hug --help
  requires:
    - pip

about:
  home: http://www.hug.rest/
  license: MIT
  license_file: LICENSE
  summary: |
    A Python framework that makes developing APIs as simple as possible,
    but no simpler.
  description: |
    hug aims to make developing Python driven APIs as simple as possible, but no
    simpler. As a result, it drastically simplifies Python API development.
    With hug, design and develop your API once, then expose it however your
    clients need to consume it. Be it locally, over HTTP, or through the command
    line - hug is the fastest and most modern way to create APIs on Python3.
  dev_url: https://github.com/timothycrosley/hug

extra:
  recipe-maintainers:
    - daf
    - kwilcox
