travis:
  secure:
    BINSTAR_TOKEN: ReXquw7Cdz6zX03lUYQsUokmN7BUAEJIoeylzw+/JxyewfyuC5Iylr0M2ZjMOkXToIVvsImjy+GLm2kIThX/1haMwGobgr4Rrl/T54rV6Y0dieqTlFpuPfaIWHyFJJPhGw8UBNBN2O+rqEDMJORpMDPIcWdj6+vqVw71ifioeBjFO4aRiLu9L7ev9yJpqgMtVx2uIDJKnyDDN9VcNi85Yr0piBY/YkcRll46SnPh6byJ+yXv1C3AScvb81Kizm8q+7oWoufhJJSDLVdjH/rUemK7WiYR8TtFdjI0Nj4zXIGcXiQQc+igXDpzhpvCrk1R7kg92S4C7FtrdinDnxPTkoNaQKA8T91K2MgtvPuhXJuVQ5DrBL7CSRTTKRpufgiu/t65OQgdS0/NvyXLvYe15EZh5Pw+dzEUnlz4fRYBwB6wW5D4oWZegHCjIZgzjh+ufbPcfzrq6PH7EUPmurU54LHH9pDNYQvxZfagLE7HO81YxKEJefwO3UaejuQoPADqWiieIKmTx7a0NUH2I7kRfZ3+K/D86CPoDb/eavxA8dWiCJG375wmTIx2ynYrO2SFHUwAcxRTLeqax4AqfboeV3wyuTNHyPQvKhGr7YjbgIGLKS+hBiTlwQe/+JT7bQC9usCfnHmMDucN95R1hZA/qYuKnXM+5WVhfLFrU/JrR0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
